# Generated by Django 5.1.1 on 2024-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
